### ISSUE TITLE
Change the directory of STACK&QUEUE folder to C++ folder 

### ISSUE THREAD

**Issue by Saikat2407** [Saikat2407/DSA_Hacktoberfest2023#101]
If anyone would like to work on this issues, let me know!

**Comment by sdas2k3** [comment]
Hey @Saikat2407 I want to work on this issue, please assign this issue to me

**Comment by ishita-139** [comment]
i woud like to work on the issue

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by Saikat2407** [comment]
go ahead and make the changes!
