### ISSUE TITLE
Subarray Sum Equals K

### ISSUE THREAD

**Issue by ikunal-04** [Saikat2407/DSA_Hacktoberfest2023#110]
Given an array of integers nums and an integer k, return the total number of subarrays whose sum equals to k.

Hi @Saikat2407 I want to add code for the problem (Leetcode) subarray sum equals k in the repository.
Please assign it to me.
Thanks

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by HarshProj** [comment]
Hey could you please assign this task to me I want to contribute

**Comment by amnbaluni** [comment]
Please assign it to me
