### ISSUE TITLE
Binary Search problem

### ISSUE THREAD

**Issue by tanisha91** [Saikat2407/DSA_Hacktoberfest2023#150]
Sir I want to add some binary Search problem

**Comment by tanisha91** [comment]
Please Assign it to me

**Comment by Jugnu-Gupta** [comment]
@Saikat2407 could you please assign me, this task i would like to contribute.

**Comment by Ishika0-0** [comment]
@Saikat2407 Can I contribute to this issue

**Comment by Saikat2407** [comment]
> Sir I want to add some binary Search problem

Hey @tanisha91 the issue has been resolved already! let me know if you would like to contribute on some other algo! 👍
