### ISSUE TITLE
leetcode problem 657. Robot Return to Origin

### ISSUE THREAD

**Issue by vermaaarti** [Saikat2407/DSA_Hacktoberfest2023#301]
Hey @Saikat2407, I would like to contribute to this problem, do assign it to me.
 Where:- 
There is a robot starting at the position (0, 0), the origin, on a 2D plane. Given a sequence of its moves, judge if this robot ends up at (0, 0) after it completes its moves.

You are given a string moves that represents the move sequence of the robot where moves[i] represents its ith move. Valid moves are 'R' (right), 'L' (left), 'U' (up), and 'D' (down).

Return true if the robot returns to the origin after it finishes all of its moves, or false otherwise.

**Comment by MahakGautam2002** [comment]
Hey, I can write code for this problem, so please assign this issue to me under hacktoberfest2023 tag.

**Comment by manas-1110** [comment]
I want to write a code for this. Please assign this to me.

**Comment by vermaaarti** [comment]
@Saikat2407 done, please check.

**Comment by vermaaarti** [comment]
@Saikat2407 done, please check.
