### ISSUE TITLE
Finding the Longest Increasing Subsequence in c++

### ISSUE THREAD

**Issue by Aniket3063** [Saikat2407/DSA_Hacktoberfest2023#34]
Hello @Saikat2407 
I want to add the code returning the length of the longest strictly increasing subsequence in c++. 
please assign it to me under hacktoberfest2023.
Thank u

**Comment by Saikat2407** [comment]
Go ahead!!

**Comment by ADNAAN18** [comment]
Hello @Saikat2407 
Please assign this to me. I could contribute to this issue with a clear explanation. Also, this would be my first issue to solve.
